### ISSUE TITLE
not show result output on osx

### ISSUE THREAD

**Issue by tesla9** [cmcpasserby/MayaCharm#19]
I can not see Maya output of Maya Log in PyCharm window.
(script execution works, I can see output in Maya)

I use Maya 2018 and the newest pro version of PyCharm.

**Comment by cmcpasserby** [comment]
did you select connect to maya log from the run menu yet?

**Comment by tesla9** [comment]
you are right it is my fault -- I just followed installation steps on GitHub and when I saw empty output I thought, that something is wrong. I was not aware of an option in run menu.
Thank you for quick answer and fantastic plugin!

**Comment by cmcpasserby** [comment]
yeah i recently had to change to this instead of doing it automatically. On the plug-in side i have no easy way to know if maya is sending to the log and maya does not like it when i spam connect commands, so i switched to having it be its own option instead of just calling it every time code is executed.
