### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by joksim** [cmcpasserby/MayaCharm#2]
When starting the MayaCharm plugin, the following messages appears in the event log:
`PluginException: ca/rightsomegoodgames/mayacharm/logconsole/MayaLogWindow : Unsupported major.minor version 52.0 [Plugin: ca.rightsomegoodgames.mayacharm` - [log](https://gist.github.com/joksim/0221d54627d662386080#file-mayacharm-error1-log)

After approx. 30 sec, the following exception appears

`PluginException: cannot create class ca.rightsomegoodgames.mayacharm.actions.SendBufferAction" [Plugin: ca.rightsomegoodgames.mayacharm]` - [log](https://gist.github.com/joksim/ff563aa318c34d2a27a4#file-mayacharm-error2-log)

Further logs are given for each message in the links provided.

I'm using `PyCharm Professional 5.0.4 build PY 143.1919` on Linux based systems, with openjdk (`OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)`) and Maya 2016

**Comment by cmcpasserby** [comment]
thanks for the stacktrace, i will look into that this weekend. Can you let me know what distro you use i am going to try and setup a vm to recreate the problem and for testing it in the future since most of the development was done on windows and osx

**Comment by joksim** [comment]
I'm using Debian 8 (jesse), but at work i'm using CentOS 6.7.
The given system parameters are from the debian machine. I will update the issue with the CentOS parameters for Pycharm and Java Runtime

**Comment by cmcpasserby** [comment]
yeah i just recreated the issue on a Ubuntu 14.04 virtual machine so that should be enough for me to get to the bottom of this problem

**Comment by cmcpasserby** [comment]
Did some tests, you will need to install Orcale Java 8 to use this plugin. It seems to be possible to install Java 8 in Debian from the Ubuntu ppa
http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html
if you google around there seems to be a manual Java 8 installer for centOS as well.

I would just target the Java 7 JVM but i am using features of Java 8 so that would require me to refactor the usage of such features out of my code.
