### ISSUE TITLE
Execute Document and Selection both greyed out

### ISSUE THREAD

**Issue by alexandremgcabral** [cmcpasserby/MayaCharm#34]
Hi!

I'm using Maya 2017 update 1 and the latest pycharm community (2019.1). I'm downloading the plugin directly from the market so I'm also running its latest version. 

Right now I have my SDK set to "...\Maya2017\bin\mayapy.exe" and I'm opening the correct port on maya's side. If I go to "attach to process" I see "...\Maya2017\bin\maya.exe" and I can successfully attach to it.

Still, I don't seem to be able to execute the document (or selection). The hotkeys won't do anything and both options on the "Run" menu are greyed out. The "Connect to maya's log" is not greyed out though.

I've also tried downloading older versions here but still it doesn't work. Also tried adding my current file on the run configuration but didn't seem to do anything either.

Any help is appreciated :) Thanks

**Comment by YKdvd** [comment]
We're having this issue too.  A new Windows10 machine ("New10) with PyCharm Community Edition 2019.1 and Maya 2018, and another Win10 box ("Old10") with PyCharm Pro 2018.3.3and Maya 2018.  But then on the Old10 box I switched MayaCharm's active SDK to 2016 instead of 2018, and it seemed to work.  And when I switched back to 2018, that worked too.  It did seem to grey out again once or twice, and a couple times after switching, trying to run a file with Alt-A I got the message that MayaCharm could execute while PyCharm was updating indexes.  Perhaps MayaCharm is getting a false positive about indexing at times and greying out?

Things seem to be okay on an existing Win7 box.  I'm going to go back to the New10 box and see if switching between two Maya SDKs helps there.

**Comment by cmcpasserby** [comment]
hmm it might be caused by the new PyCharm version so tomorrow hopefully i will find time to test and see whats going on.

**Comment by cmcpasserby** [comment]
Found the issue, and will try and get this into a build and submitted tomorrow.

**Comment by cmcpasserby** [comment]
I uploaded the fix to the plug-in market place so it should be available in 2 days or less.

**Comment by alexandremgcabral** [comment]
Hey,
Just wanted to say that it work perfectly with the new update (3.0.2)! Thanks for fixing this so quick!

**Comment by cmcpasserby** [comment]
This was a easy one, little one liner change with how PyCharm works with detecting file types, so no big deal. Thanks for reporting it i no longer work with Maya with my job anymore so it sometimes takes me a while to find bugs on my own.
