### ISSUE TITLE
mayaCharm-2019.3_support Fail to load plugin descriptor

### ISSUE THREAD

**Issue by mberry84** [cmcpasserby/MayaCharm#46]
Hi, I'm having trouble installing the mayaCharm-2019.3_support branch getting the following error
"Fail to load plugin descriptor from MayaCharm-2019.3_support.zip"
I'm installing it by going to Plugins > Install Plugin from Disk

I have unziped the file and the Plugin Content don't seem to mach what is listed on the following page for how a plugin should be structured. 
[](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_content.html )

Am I doing something wrong?

**Comment by cmcpasserby** [comment]
2019.3 support is incomplete, also it would have to be built first since you cant directly use sources from the repo as a plugin.

Not sure when it will be done, since i do not have much time to work on the project, and versions of PyCharm >= 2019.3 have made some large changes to the python debugger that make my previous approach to using it with Maya no longer work.

**Comment by mberry84** [comment]
ok, that is unfortunate, Thanks for getting beck to me
