### ISSUE TITLE
2020.1 Support

### ISSUE THREAD

**Issue by gsaaav** [cmcpasserby/MayaCharm#48]
Hello! 
It seems that 2020.1 is not yet supported. In 2020.1 the execute commands buttons in the menu remain greyed out.

**Comment by cmcpasserby** [comment]
It should not even install on 2020.1 since i have not submitted one compatible with it on the plugin repo yet.

Due changes that came in during 2019.3 with the debugger i have not been able to get the plugin working on versions that are 2019.3 and above yet. You can track the progress of that in issue #43

**Comment by gsaaav** [comment]
Ahh ok, I’ll downgrade. I installed maya charm on 2019 the updated my pycharm.

**Comment by cmcpasserby** [comment]
yeah hoping to get it working again at somepoint, it will just take having some more free time to figure out exactly what is going on. 2019.2 is the latest version that works with all features right now.
